management.security.enabled: false

slack.token: change-me
foosball.user: change-me
game.timeout: 30

logging:
  level:
    com.leanforge: DEBUG

spring.data.mongodb:
  uri: mongodb://mongodb:27017/locker